# -*- coding: cp1252 -*-
#UNIVERSIDADE DO ESTADO DO RIO DE JANEIRO - UERJ
#BRUNO BANDEIRA BRANDÃO
#LISTA 5: FUNDAMENTOS DA COMPURAÇÃO 2018/2
#EXERCÍCIO 4
v1=[0]*10 #IMPRIME UM VETOR COM OS 10 PRIMEIROS NÚMEROS PRIMOS
for i in range(0,10):
    v1[i]=(2*(i+1))-1
print 'Vetor:',v1

